# Generated by Django 3.1.5 on 2021-01-27 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=20)),
                ('mac_address', models.CharField(max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time when the register was created')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Date and time when the register was updated')),
            ],
        ),
        migrations.CreateModel(
            name='OperativeSystemMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('accuracy', models.PositiveSmallIntegerField()),
                ('line', models.PositiveSmallIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time when the register was created')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Date and time when the register was updated')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_os_match', to='nmap_application.host')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolp', models.CharField(max_length=255)),
                ('portid', models.PositiveSmallIntegerField()),
                ('state', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=255)),
                ('reason_ttl', models.PositiveSmallIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time when the register was created')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Date and time when the register was updated')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_port', to='nmap_application.host')),
            ],
        ),
        migrations.CreateModel(
            name='OperativeSystemClass',
            fields=[
                ('operative_system_match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nmap_application.operativesystemmatch')),
                ('type', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('operative_system_family', models.CharField(max_length=255)),
                ('operative_system_generation', models.CharField(max_length=255)),
                ('accuracy', models.PositiveSmallIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time when the register was created')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Date and time when the register was updated')),
            ],
        ),
        migrations.CreateModel(
            name='PortService',
            fields=[
                ('port', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nmap_application.port')),
                ('name', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('operative_system_type', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=255)),
                ('conf', models.PositiveSmallIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time when the register was created')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Date and time when the register was updated')),
            ],
        ),
        migrations.CreateModel(
            name='ScannerHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(help_text='This field saves the IP, range of IPs or subnet mask that is scanned', max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True, help_text='Date and time when the register was created')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='Date and time when the register was updated')),
                ('host', models.ManyToManyField(related_name='host_history', to='nmap_application.Host')),
            ],
        ),
    ]
