# Generated by Django 3.1.5 on 2021-01-27 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nmap_application', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='port',
            old_name='protocolp',
            new_name='protocol',
        ),
    ]
