# Generated by Django 3.1.5 on 2021-01-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmap_application', '0002_auto_20210127_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scannerhistory',
            old_name='host',
            new_name='hosts',
        ),
        migrations.AlterField(
            model_name='host',
            name='mac_address',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
