# Generated by Django 3.1.5 on 2021-01-30 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmap_application', '0003_auto_20210130_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='portservice',
            name='extrainfo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='portservice',
            name='hostname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portservice',
            name='method',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portservice',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portservice',
            name='operative_system_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='portservice',
            name='product',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
