# Generated by Django 3.1.5 on 2021-01-31 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nmap_application', '0004_auto_20210130_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portservice',
            old_name='extrainfo',
            new_name='extra_info',
        ),
    ]
