# Generated by Django 3.1.5 on 2021-02-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmap_application', '0005_auto_20210130_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannerhistory',
            name='type',
            field=models.CharField(choices=[('QS', 'Quick scan'), ('FS', 'Full scan')], default='QS', max_length=2),
        ),
    ]
