# Generated by Django 3.1.5 on 2021-02-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmap_application', '0006_scannerhistory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='IP',
            field=models.GenericIPAddressField(),
        ),
    ]
