# Generated by Django 3.1.5 on 2021-02-02 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nmap_application', '0007_auto_20210201_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scannerhistory',
            name='target',
            field=models.GenericIPAddressField(),
        ),
    ]
