# Generated by Django 3.1.5 on 2021-02-02 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nmap_application', '0008_auto_20210201_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scannerhistory',
            options={'ordering': ['-id']},
        ),
    ]
