# Generated by Django 3.1.5 on 2021-02-02 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nmap_application', '0009_auto_20210201_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operativesystemclass',
            name='operative_system_match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='os_match_class', serialize=False, to='nmap_application.operativesystemmatch'),
        ),
        migrations.AlterField(
            model_name='portservice',
            name='port',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='port_service', serialize=False, to='nmap_application.port'),
        ),
    ]
